//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaProyecto.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cliente()
        {
            this.dirEntrega = new HashSet<dirEntrega>();
            this.orden = new HashSet<orden>();
        }
    
        public int Id_cliente { get; set; }
        [Display(Name = "Nombre completo")]
        [Required(ErrorMessage ="Debe ser mayor o menor")]
        public string nombre { get; set; }
        public string email { get; set; }
        [Display(Name = "Calle y número")]
        public string calle_t { get; set; }
        [Display(Name = "Colonia")]
        public string colonia_t { get; set; }
        [Display(Name = "Estado")]
        public string estado_t { get; set; }
        [Display(Name = "Número de tarjeta")]
        [Required(ErrorMessage = "Requerido")]
        [Range(1000000000000000,9999999999999999,ErrorMessage ="Debe ser de 16 dígitos")]
        public string num_tarj_cred_ppal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dirEntrega> dirEntrega { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orden> orden { get; set; }
    }
}
