//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaProyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orden_detalle
    {
        public int Id { get; set; }
        public Nullable<int> orden_id { get; set; }
        public Nullable<int> preducto_id { get; set; }
        public string prodcuto_nombre { get; set; }
        public Nullable<decimal> prodcuto_precio { get; set; }
        public Nullable<short> cantidad { get; set; }
    }
}
