//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaProyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class paqueteria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public paqueteria()
        {
            this.orden = new HashSet<orden>();
        }
    
        public int Id_paqueteria { get; set; }
        public string nombre { get; set; }
        public string rfc { get; set; }
        public string tel { get; set; }
        public string web { get; set; }
        public string direccion { get; set; }
        public string contacto { get; set; }
        public string tel_contacto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orden> orden { get; set; }
    }
}
